package main

import (
	"fmt"
	"path"

	"github.com/goreleaser/goreleaser/config"
	"github.com/goreleaser/goreleaser/context"
	"github.com/goreleaser/goreleaser/pipeline/defaults"
)

// processEquinoxio create a fake goreleaser config for equinox.io
// and use a similar template.
func processEquinoxio(repo string) (string, error) {
	if repo == "" {
		return "", fmt.Errorf("must have repo")
	}
	project := config.Project{}
	project.Release.GitHub.Owner = path.Dir(repo)
	project.Release.GitHub.Name = path.Base(repo)
	project.Builds = []config.Build{
		{Binary: path.Base(repo)},
	}
	project.Archive.Format = "tgz"

	var ctx = context.New(project)
	err := defaults.Pipe{}.Run(ctx)
	if err != nil {
		return "", err
	}
	return makeShell(shellEquinoxio, &ctx.Config)
}

var shellEquinoxio = `#!/bin/sh
set -e
#  Code generated by godownloader. DO NOT EDIT.
#

usage() {
  this=$1
  cat <<EOF

$this: download go binaries for {{ $.Release.GitHub.Owner }}/{{ $.Release.GitHub.Name }}

Usage: $this [-b bindir]
  -b set the installation or BINDIR, defaults to ./bin

  Version is automatically selected from
  https://dl.equinox.io/{{ $.Release.GitHub.Owner }}/{{ $.Release.GitHub.Name }}/stable

Generated by godownloader
 https://github.com/goreleaser/godownloader

EOF
  exit 2
}

parse_args() {
  #BINDIR is ./bin unless set be ENV
  # over-ridden by flag below

  BINDIR=${BINDIR:-./bin}
  while getopts "b:h?" arg; do
    case "$arg" in
      b) BINDIR="$OPTARG" ;;
      h | \?) usage "$0" ;;
    esac
  done
  shift $((OPTIND - 1))
  # VERSION currently unused
  #VERSION=$1
}
# wrap all destructive operations into a function
# to prevent curl|bash network truncation and disaster
execute() {
  TMPDIR=$(mktmpdir)

  echo "$PREFIX: seeking $CHANNEL latest from $TARGET"
  TARBALL_URL=$(http_download - "$TARGET" | grep "$TARBALL" | cut -d '"' -f 2)

  echo "$PREFIX: downloading from ${TARBALL_URL}"
  http_download "${TMPDIR}/${TARBALL}" "$TARBALL_URL"

  (cd "$TMPDIR" && untar "$TARBALL")
  install -d "${BINDIR}"
  install "${TMPDIR}/${BINARY}" "${BINDIR}/"
  echo "$PREFIX: installed ${BINDIR}/${BINARY}"
}` + shellfn + `OWNER={{ .Release.GitHub.Owner }}
REPO={{ .Release.GitHub.Name }}
BINARY={{ (index .Builds 0).Binary }}
FORMAT={{ .Archive.Format }}
BINDIR=${BINDIR:-./bin}
CHANNEL=stable
PREFIX="$OWNER/$REPO"
OS=$(uname_os)
ARCH=$(uname_arch)

uname_os_check "$OS"
uname_arch_check "$ARCH"

parse_args "$@"

TARGET=https://dl.equinox.io/${OWNER}/${REPO}/${CHANNEL}
TARBALL="${BINARY}-${CHANNEL}-${OS}-${ARCH}.${FORMAT}"

if [ "$OS" = "windows" ]; then
  BINARY="${BINARY}.exe"
fi

execute
`
