#!/bin/sh
set -e
#  Code generated by godownloader. DO NOT EDIT.

BINARY=hugo
FORMAT=tar.gz
OWNER=spf13
REPO=hugo
BINDIR=${BINDIR:-./bin}

VERSION=$1
if [ -z "${VERSION}" ]; then
echo ""
echo "$0: download go binaries for ${OWNER}/${REPO}"
echo ""
echo "Usage: $0 [version]"
echo "  where [version] is 'latest' or a version number from"
echo "  https://github.com/${OWNER}/${REPO}/releases"
echo ""
echo "Generated by godownloader"
echo " https://github.com/goreleaser/godownloader"
echo ""
exit 1
fi

# download dest source
# if dest is "-", then output to stdout
# if source is api.github.com add auth token
download() {
  DEST=$1
  SOURCE=$2

  HEADER=""
  case $SOURCE in 
  https://api.github.com*)
     test -z "$GITHUB_TOKEN" || HEADER="Authorization: token $GITHUB_TOKEN"
     ;;
  esac

  if which curl > /dev/null; then
    WGET="curl -sSL"
    test -z "$GITHUB_TOKEN" || WGET="${WGET} -H \"${HEADER}\""
    if [ "${DEST}" != "-" ]; then
      WGET="$WGET -o $DEST"
    fi
  elif which wget > /dev/null; then
    WGET="wget -q -O $DEST"
    test -z "$GITHUB_TOKEN" || WGET="${WGET} --header \"${HEADER}\""
  else
    echo "Unable to find wget or curl.  Exit"
    exit 1
  fi

  ${WGET} ${SOURCE}
}

if [ "${VERSION}" = "latest" ]; then
  echo "Checking GitHub for latest version of ${OWNER}/${REPO}"
  VERSION=$(download - https://api.github.com/repos/${OWNER}/${REPO}/releases/latest | grep -m 1 "\"name\":" | cut -d ":" -f 2 | tr -d ' ",')
  if [ -z "${VERSION}" ]; then
    echo "Unable to determine latest release for ${OWNER}/${REPO}"
    exit 1
   fi
fi

# if version starts with 'v', remove it
VERSION=${VERSION#v}

OS=$(uname -s)
ARCH=$(uname -m)

# change format (tar.gz or zip) based on ARCH
case ${ARCH} in
Windows) FORMAT=zip ;;
esac

# adjust archive name based on OS
case ${OS} in
Darwin) OS=macOS ;;
arm) OS=ARM ;;
arm64) OS=ARM64 ;;
dragonfly) OS=DragonFlyBSD ;;
i386) OS=32bit ;;
x86_64) OS=64bit ;;
esac

# adjust archive name based on ARCH
case ${ARCH} in
Darwin) ARCH=macOS ;;
arm) ARCH=ARM ;;
arm64) ARCH=ARM64 ;;
dragonfly) ARCH=DragonFlyBSD ;;
i386) ARCH=32bit ;;
x86_64) ARCH=64bit ;;
esac

NAME=${BINARY}_${VERSION}_${OS}-${ARCH}
TARBALL=${NAME}.${FORMAT}
URL=https://github.com/${OWNER}/${REPO}/releases/download/v${VERSION}/${TARBALL}

# Destructive operations start here
#
#
test -z "$TMPDIR" && TMPDIR="$(mktemp -d)"
mkdir -p ${TMPDIR}
rm -f ${TMPDIR}/${TARBALL}
download ${TMPDIR}/${TARBALL} ${URL}
case ${FORMAT} in
  tar.gz)
   tar -C ${TMPDIR} -xzf ${TMPDIR}/${TARBALL}
   ;;
  zip)
   (cd ${TMPDIR} && unzip ${TARBALL})
   ;;
  *)
   echo "unknown format '${FORMAT}' - exiting"
   exit 1
   ;;
esac
install -d ${BINDIR}
install ${TMPDIR}/${BINARY} ${BINDIR}/

